### ISSUE TITLE
CI Fail

### ISSUE THREAD

**Issue by tjcrone** [earth-env-data-science/earth-env-data-science-book#13]
I made a very small change to the first assignment just before class and pushed to master. The CI failed with
```
jinja2.exceptions.TemplateNotFound: markdown.tpl
```
It's not clear how this happened since my changes were minuscule. Any ideas here? Thanks!

**Comment by rabernat** [comment]
No idea. I never encountered that before. Sorry! Can you point me to the commit?

**Comment by rabernat** [comment]
If you make changes via a PR, the CI will run so you can check that things build and debug a bit more interactively.

**Comment by rabernat** [comment]
I see it: https://github.com/earth-env-data-science/earth-env-data-science-book/commit/56812f4648d7a6f2ac8f66072eb73682c0993047

Yeah that's bizarre.

**Comment by tjcrone** [comment]
Okay I guess I will try again via PR. I pushed to master because I needed this for class and I had about 2 minutes. Thanks.

**Comment by tjcrone** [comment]
I made another minor change and merged a PR from my fork, and got the same issue. The CI ran in the same exact way. Can you please confirm that you can PR to master, and have the CI run without error? I will track this down but confirming that this is not happening for you will be helpful.

**Comment by tjcrone** [comment]
I'm wondering if I also maybe need to clone the other repo where the files are written? Or maybe this is because I am not push on the other repo?

**Comment by tjcrone** [comment]
I feel like this might point us in the right direction: https://github.com/fastai/nbdev/issues/8

**Comment by tjcrone** [comment]
I'm feeling some warmth here but not as much: https://github.com/executablebooks/jupyter-book/issues/310

**Comment by rabernat** [comment]
> Can you please confirm that you can PR to master, and have the CI run without error?

The CI ran without error three days ago: https://app.circleci.com/pipelines/github/earth-env-data-science/earth-env-data-science-book/49/workflows/9048acd4-0d87-43f0-a1b6-6110c5ad76db

For a very simple commit: https://github.com/earth-env-data-science/earth-env-data-science-book/commit/b535e1f9a205b5cf56f232a47129662bd0ba137b

I would compare the details of that run with your failing run and try to nail down the difference. Perhaps a non-pinned dependency changed versions over the past few days. The solution would be to pin the dependencies to whatever versions were present for the working run.

**Comment by tjcrone** [comment]
Right. This is why I am asking you to make a small PR so that I can determine if it is a package change, or if it is a difference between our forks. Would you have time to try this? Thanks!

**Comment by rabernat** [comment]
See #15

**Comment by tjcrone** [comment]
Pinning nbconvert to 5.6.1 for now. See https://github.com/jupyter/nbconvert/issues/1369.

**Comment by willingc** [comment]
Yes, there are differences between nbconvert version 5.6.1 and 6.x. @rabernat @tjcrone There will likely be one more dot release in the next few days to bring nbconvert to 6.0.3 and there are some template PRs in that release.
