### ISSUE TITLE
Upgrade to latest JupyterBook version

### ISSUE THREAD

**Issue by rabernat** [earth-env-data-science/earth-env-data-science-book#29]
We are currently pinned to version 0.5.2:

https://github.com/earth-env-data-science/earth-env-data-science-book/blob/a97d6c569e7be0ded0d58ce55a34276dbe8bbe91/.circleci/config.yml#L97

JupyterBook is on [0.11.2](https://jupyterbook.org/reference/_changelog.html#v0-11-2). So we are very far behind.

We should upgrade to the latest version. This will likely break our CI.

Shamelessly cc'ing @choldgraf for any tips he might have.

**Comment by choldgraf** [comment]
Hmm - I'd start here https://github.com/executablebooks/jupyter-book/wiki/The-Jupyter-Book-Wiki#the-jupyter-book-legacy-upgrade-guide that is what folks were using back when the new build system was released!

**Comment by choldgraf** [comment]
lol #33 is a great title for a PR
