### ISSUE TITLE
Switch to GitHub actions

### ISSUE THREAD

**Issue by rabernat** [earth-env-data-science/earth-env-data-science-book#30]
I don't know CircleCI very well and don't want to deal with it any more. Let's switch to GitHub actions.

This is likely part of #29, since that will affect CI heavily.

**Comment by tjcrone** [comment]
I support this change and will help in whatever way I can. I know Circle fairly well and GitHub Actions a bit less so. I don't think it will be very painful.

**Comment by rabernat** [comment]
There is a really helpful docs page on this: https://jupyterbook.org/publish/gh-pages.html

As a first step, I think we should _not try to execute the notebooks inside gh actions_. We already have exceuted notebooks in the repo, so let's stay with that.

Going forward, I would like to use [binderbot](https://github.com/pangeo-gallery/binderbot) to execute the notebooks in CI.

**Comment by tjcrone** [comment]
Okay roger roger on binderbot. I will wait for the PR with your latest changes and pick up from there.

**Comment by tjcrone** [comment]
Okay great! The book appears to build and deploy properly to the github.io repo using GitHub Actions. Before I close this, I would like to discuss binderbot. How do you envision incorporating this tool if not through Actions?

**Comment by rabernat** [comment]
I brought this up in https://github.com/executablebooks/jupyter-book/issues/1445. Formal integration between jupyterbook and binderbot will not happen this semester. 

We could potentially hack a solution that runs binderbot from our CI workflows. But first I think we should try building the book (executing the notebooks) locally in GitHub actions. Some of the pages won't work because they need too much memory, and we can exclude those / build them manually. So maybe binderbot wouldn't be needed.

It would be really cool if we could use the pangeo-notebook docker image _inside_ the github workflow. That would solve all the environment problems. I _think_ this is possible but I'm not certain. Would need smoe investigation.

**Comment by tjcrone** [comment]
Okay thanks for explaining this. I think I will close this issue and we can open a binderbot issue or issue relating to executing the notebooks as it comes up as we continue to improve the book in the coming days.
