### ISSUE TITLE
`conda remove` must be `conda env remove`

### ISSUE THREAD

**Issue by mathause** [earth-env-data-science/earth-env-data-science-book#43]
See https://github.com/earth-env-data-science/earth-env-data-science-book/blame/master/src/lectures/environment/python_environments.md#L132-L135

---

B.t.w. thanks for the book & putting it in the public domain! I might use some of these resources in our course (with proper attribution obviously).

**Comment by rabernat** [comment]
Thanks @mathause! PR welcome 😉 

> putting it in the public domain

Technically this material is not public domain but rather licensed via a CC BY-SA 4.0 license: https://github.com/earth-env-data-science/earth-env-data-science-book/blob/master/src/LICENSE.md

The license is described here: https://creativecommons.org/licenses/by-sa/4.0/

**Comment by mathause** [comment]
> Technically this material is not public domain but rather licensed via a CC BY-SA 4.0 license

Thanks for the clarification.
