### ISSUE TITLE
Issue on page /projects.html

### ISSUE THREAD

**Issue by lockecd** [earth-env-data-science/earth-env-data-science-book#45]
The kernal for my final project crashes when trying to run my jupyter notebook in binder. Is there a way to choose a server with a higher memory capacity in binder? Thanks!

**Comment by rabernat** [comment]
No. It will not be possible. But you can use [nbgitpuller](https://jupyterhub.github.io/nbgitpuller/link) to open the notebook in our jupyterhub. That's what I recommend.

**Comment by lockecd** [comment]
Okay! Thank you!
